CI step to test CD to Azure workflow (#119)
* CI step to deploy an Azure env

* Variable name

* Editorconfig

* CI closing

* Push skeleton to Azure env once provisioned

* Add Flysystem bundle if not installed already

* Use recipes branch of skeleton

* Temporarily use branched version for 2024.x to get builds to succeed

* Correct bundle install

* Tests back to 2024.x

* Skip scripts on require

* Fix 2024.x ref

* Try out quick provisioning of Azure

* Force a change

* Force a change

* Back to released version of Azure workflow

diff --git a/.github/workflows/deploy-to-azure-container-apps.yml b/.github/workflows/deploy-to-azure-container-apps.yml
--- a/.github/workflows/deploy-to-azure-container-apps.yml
+++ b/.github/workflows/deploy-to-azure-container-apps.yml
@@ -262,6 +262,18 @@ jobs:
         if: ${{ inputs.SKIP_LINTING == false }}
         uses: ./reusable-workflow/.github/actions/lint
 
+      - name: Install Azure Flysystem bundle if not already installed
+        run: |
+          set -euo pipefail
+
+          if ! composer show --no-interaction --no-ansi "torqit/pimcore-flysystem-azure-bundle" >/dev/null 2>&1 \
+            && ! composer show --no-interaction --no-ansi "torq/pimcore-flysystem-azure-bundle" >/dev/null 2>&1; then
+            echo "Azure Flysystem bundle not found, installing..."
+            composer require --no-interaction --no-ansi --no-scripts torq/pimcore-flysystem-azure-bundle
+          else
+            echo "Azure Flysystem bundle already installed, skipping"
+          fi
+
       - name: Log in to Azure
         uses: ./reusable-workflow/.github/actions/azure-login
         with:
