Implement blue/green

diff --git a/.github/workflows/deploy-to-vm-self-hosted.yml b/.github/workflows/deploy-to-vm-self-hosted.yml
--- a/.github/workflows/deploy-to-vm-self-hosted.yml
+++ b/.github/workflows/deploy-to-vm-self-hosted.yml
@@ -91,6 +91,10 @@ on:
         type: string
         default: "php"
         description: "Name of the PHP Pimcore image"
+      PHP_IMAGE_TAG:
+        required: false
+        type: string
+        description: "Custom tag for built PHP image"
       PHP_DOCKERFILE:
         required: false
         type: string
@@ -111,6 +115,10 @@ on:
         type: string
         default: "supervisord"
         description: "Name of the supervisord Pimcore image"
+      SUPERVISORD_IMAGE_TAG:
+        required: false
+        type: string
+        description: "Custom tag for built supervisord image"
       SUPERVISORD_DOCKERFILE:
         required: false
         type: string
@@ -189,6 +197,7 @@ jobs:
 
       - name: Build and push init image
         uses: ./reusable-workflow/.github/actions/build-and-push-pimcore-image
+        if: ${{ inputs.INIT }}
         with:
           DOCKERFILE_PATH: ${{ inputs.INIT_DOCKERFILE }}
           DOCKERFILE_TARGET: ${{ inputs.INIT_DOCKER_TARGET }}
@@ -283,6 +292,52 @@ jobs:
       
       - name: Perform blue/green deployment of PHP and supervisord containers
         run: |
+          if [ "$(docker ps -f name=blue -q)" ]; then
+              NEW_DEPLOYMENT="green"
+              OLD_DEPLOYMENT="blue"
+          else
+              NEW_DEPLOYMENT="blue"
+              OLD_DEPLOYMENT="green"
+          fi
+
+          echo "Starting "$NEW_DEPLOYMENT" containers..."
+          docker-compose \
+              --project-name=$NEW_DEPLOYMENT \
+              --env-file .env \
+              -f docker-compose.yml -f ${{ inputs.DOCKER_COMPOSE_FILE }} \
+              up -d ${{ inputs.PHP_SERVICE }} ${{ inputs.SUPERVISORD_SERVICE }}
+
+          echo "Waiting for $NEW_DEPLOYMENT deployment to be ready..."
+          set +e
+          docker-compose \
+              --project-name=$NEW_DEPLOYMENT \
+              -f docker-compose.yml -f ${{ inputs.DOCKER_COMPOSE_FILE }} \
+              exec -T ${{ inputs.PHP_SERVICE }} \
+                  wget \
+                    --verbose \
+                    --content-on-error \
+                    --retry-on-http-error=429,503,502,504 \
+                    -T 3 -t 100 \
+                    --retry-connrefused \
+                    -O /var/www/html/log/error.html \
+                    localhost
+          DEPLOY_STATUS=$?
+          set -e
+
+          if [[ $DEPLOY_STATUS == 0 ]]; then
+              echo "Stopping "$OLD_DEPLOYMENT" containers..."
+              docker-compose \
+                  --project-name=$OLD_DEPLOYMENT \
+                  -f docker-compose.yml -f ${{ inputs.DOCKER_COMPOSE_FILE }} \
+                  rm --stop --force ${{ inputs.PHP_SERVICE }} ${{ inputs.SUPERVISORD_SERVICE }}
+          else
+              echo "Error bringing up new containers - stopping $NEW_DEPLOYMENT containers..."
+              docker-compose \
+                  --project-name=$NEW_DEPLOYMENT \
+                  -f docker-compose.yml -f ${{ inputs.DOCKER_COMPOSE_FILE }} \
+                  rm --stop --force ${{ inputs.PHP_SERVICE }} ${{ inputs.SUPERVISORD_SERVICE }}
+              exit 1
+          fi
 
   workflow-failure-notification:
     name: Send workflow failure notification to Slack channel
