Revert

diff --git a/.github/workflows/deploy-to-azure-container-apps.yml b/.github/workflows/deploy-to-azure-container-apps.yml
--- a/.github/workflows/deploy-to-azure-container-apps.yml
+++ b/.github/workflows/deploy-to-azure-container-apps.yml
@@ -332,22 +332,18 @@ jobs:
         if: ${{ inputs.SKIP_LINTING == false }}
         uses: ./reusable-workflow/.github/actions/lint
 
-      - name: Install required Azure bundles if not already installed
+      - name: Install Azure Flysystem bundle if not already installed
         if: ${{ inputs.FEATURE_FLAG_INSTALL_MISSING_BUNDLES }}
         run: |
           set -euo pipefail
-          bundles=(
-            "torq/pimcore-azure-mysql"
-            "torq/pimcore-flysystem-azure-bundle"
-          )
-          for bundle in "${bundles[@]}"; do
-            if composer show --no-interaction --no-ansi "$bundle" >/dev/null 2>&1; then
-              echo "Bundle $bundle is already installed"
-            else
-              echo "Bundle $bundle not found, installing..."
-              composer require --no-interaction --no-ansi --no-scripts "$bundle"
-            fi
-          done
+
+          if ! composer show --no-interaction --no-ansi "torqit/pimcore-flysystem-azure-bundle" >/dev/null 2>&1 \
+            && ! composer show --no-interaction --no-ansi "torq/pimcore-flysystem-azure-bundle" >/dev/null 2>&1; then
+            echo "Azure Flysystem bundle not found, installing..."
+            composer require --no-interaction --no-ansi --no-scripts torq/pimcore-flysystem-azure-bundle
+          else
+            echo "Azure Flysystem bundle already installed, skipping"
+          fi
 
       - name: Log in to Azure
         uses: ./reusable-workflow/.github/actions/azure-login
